site_name: yandexdevs.gay 
theme:
  extra_css:
    - assets/stylesheets/extra.css
  name: material
  language: ru
  palette:
    primary: deep purple
    accent: purple
    # Palette toggle for light mode
    scheme: default
    toggle:
      icon: material/brightness-7 
      name: Switch to dark mode

    # Palette toggle for dark mode
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
